### ISSUE TITLE
Published on npm?

### ISSUE THREAD

**Issue by nikrowell** [ayamflow/standalone-shader#1]
Hi Florian - I'm interested in experimenting with this but wasn't able to find it on npm. Is it still published? Cheers!

**Comment by ayamflow** [comment]
Hey @nikrowell,
it's not published on npm since this is kind of an experimental module.
However you can install it from github with npm like so: `npm i ayamflow/standalone-shader -S`, should work just the same!

**Comment by nikrowell** [comment]
Ah, didn't know that (and clearly I didn't try that first after seeing it in the README 😉)  
Thanks for the tip!
